theme: minima
title: Greatest Albums of All Time
description: A list of the very best
plugins:
  - jekyll-datapage-generator
page_gen:
  - data: albums
    template: album
    name: slug
    dir: "albums"
    title: "title"