name: Album Submission
description: Suggest a new album for the site
title: "[Album Submission] Artist - Album Name"
labels: [submission]
assignees:
  - wolfmaaan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting an album for consideration on the list to end all lists.
  - type: input
    id: artist
    attributes:
      label: Artist
      placeholder: e.g. Radiohead
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Album Title
      placeholder: e.g. OK Computer
    validations:
      required: true
  - type: input
    id: year
    attributes:
      label: Release Year
      placeholder: e.g. 1997
    validations:
      required: true
  - type: input
    id: image_url
    attributes:
      label: Cover Image URL
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Source cover art from [Ben Dodson](https://bendodson.com/projects/itunes-artwork-finder/)
  - type: input
    id: wiki_url
    attributes:
      label: Wikipedia URL
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Source Wiki link from [Wikipedia](https://en.wikipedia.org/)
